// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $docs_slug_ from "./routes/docs/[...slug].tsx";
import * as $docs_v1_slug_ from "./routes/docs_v1/[...slug].tsx";
import * as $faqs_slug_ from "./routes/faqs/[...slug].tsx";
import * as $gfm_css from "./routes/gfm.css.ts";
import * as $index from "./routes/index.tsx";
import * as $raw from "./routes/raw.ts";
import * as $LemonDrop from "./islands/LemonDrop.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/docs/[...slug].tsx": $docs_slug_,
    "./routes/docs_v1/[...slug].tsx": $docs_v1_slug_,
    "./routes/faqs/[...slug].tsx": $faqs_slug_,
    "./routes/gfm.css.ts": $gfm_css,
    "./routes/index.tsx": $index,
    "./routes/raw.ts": $raw,
  },
  islands: {
    "./islands/LemonDrop.tsx": $LemonDrop,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
